# Generated by Django 4.2.7 on 2025-05-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('pk_MaThanhToan', models.AutoField(primary_key=True, serialize=False)),
                ('fk_MaDonHang', models.IntegerField()),
                ('PhuongThucThanhToan', models.CharField(max_length=100)),
                ('NgayThanhToan', models.DateField()),
                ('TrangThaiThanhToan', models.CharField(max_length=50)),
            ],
        ),
    ]
