# Generated by Django 4.2.7 on 2025-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'UserBalance',
            },
        ),
        migrations.AddField(
            model_name='thanhtoan',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='PhuongThucThanhToan',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('ewallet', 'E-Wallet'), ('stripe', 'Stripe')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='TrangThaiThanhToan',
            field=models.CharField(choices=[('Chờ xử lý', 'Chờ xử lý'), ('Hoàn tất', 'Hoàn tất'), ('Thất bại', 'Thất bại')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='fk_MaDonHang',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='thanhtoan',
            table='ThanhToan',
        ),
    ]
