# Generated by Django 4.2.7 on 2025-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_userbalance_thanhtoan_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhtoan',
            name='TrangThaiThanhToan',
            field=models.CharField(choices=[('Chờ thanh toán', 'Chờ thanh toán'), ('Đã thanh toán', 'Đã thanh toán'), ('Đã hoàn tiền', 'Đã hoàn tiền'), ('Thất bại', 'Thất bại')], max_length=50),
        ),
    ]
