# Generated by Django 4.0.4 on 2025-04-13 09:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDanhMuc', models.CharField(max_length=100)),
                ('MoTa', models.TextField(blank=True, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh Mục',
                'verbose_name_plural': 'Danh Mục',
                'db_table': 'DanhMuc',
            },
        ),
        migrations.CreateModel(
            name='HangSanXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHangSanXuat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Hãng Sản Xuất',
                'verbose_name_plural': 'Hãng Sản Xuất',
                'db_table': 'HangSanXuat',
            },
        ),
        migrations.CreateModel(
            name='ThongSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenThongSo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Thông Số',
                'verbose_name_plural': 'Thông Số',
                'db_table': 'ThongSo',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(max_length=200)),
                ('MoTa', models.TextField()),
                ('GiaBan', models.DecimalField(decimal_places=0, max_digits=10)),
                ('SoLuongTon', models.PositiveIntegerField(default=0)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to=products.models.hinh_anh_san_pham_path)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
                ('DanhMuc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_pham', to='products.danhmuc')),
                ('HangSanXuat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.hangsanxuat')),
            ],
            options={
                'verbose_name': 'Sản Phẩm',
                'verbose_name_plural': 'Sản Phẩm',
                'db_table': 'SanPham',
            },
        ),
        migrations.CreateModel(
            name='ChiTietThongSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GiaTriThongSo', models.TextField()),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_thong_so', to='products.sanpham')),
                ('ThongSo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.thongso')),
            ],
            options={
                'verbose_name': 'Chi Tiết Thông Số',
                'verbose_name_plural': 'Chi Tiết Thông Số',
                'db_table': 'ChiTietThongSo',
                'unique_together': {('SanPham', 'ThongSo')},
            },
        ),
    ]
