# Generated by Django 4.0.4 on 2025-04-11 09:22
from django.db import migrations

def create_order_statuses(apps, schema_editor):
    TrangThai = apps.get_model('orders', 'TrangThai')
    
    # Tạo các trạng thái đơn hàng
    order_statuses = [
        {'TenTrangThai': 'Chờ thanh toán', 'LoaiTrangThai': 'Đơn hàng'},
        {'TenTrangThai': 'Đã thanh toán', 'LoaiTrangThai': 'Đơn hàng'},
        {'TenTrangThai': 'Đang xử lý', 'LoaiTrangThai': 'Đơn hàng'},
        {'TenTrangThai': 'Đang vận chuyển', 'LoaiTrangThai': 'Đơn hàng'},
        {'TenTrangThai': 'Đã giao hàng', 'LoaiTrangThai': 'Đơn hàng'},
        {'TenTrangThai': 'Đã hủy', 'LoaiTrangThai': 'Đơn hàng'},
        {'TenTrangThai': 'Hoàn tiền', 'LoaiTrangThai': 'Đơn hàng'},
    ]
    
    for status in order_statuses:
        TrangThai.objects.get_or_create(
            TenTrangThai=status['TenTrangThai'],
            defaults={'LoaiTrangThai': status['LoaiTrangThai']}
        )

def reverse_func(apps, schema_editor):
    TrangThai = apps.get_model('orders', 'TrangThai')
    TrangThai.objects.filter(LoaiTrangThai='Đơn hàng').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_chitietdonhang_donhang_trangthai_and_more'),
    ]

    operations = [
        migrations.RunPython(create_order_statuses, reverse_func),
    ]